export class Edition {
  constructor(
    public readonly id: number,
    public readonly nom: string,
    public readonly categorie: string,
    public readonly annee: number,
    public readonly etape: string,
    public readonly dateDebut: Date,
    public readonly dateFinDebut: Date,
    public readonly dateFinFin: Date,
    public readonly dateDbutRepas: Date | null,
    public readonly fraisInscription: number,
    public readonly prixRepas: number,
    public readonly nbPlacesMax: number,
    public readonly imageUrl: string | null,
    public readonly imageDossierUrl: string | null,
    public readonly imageRibUrl: string | null,
    public readonly contactEmail: string | null,
    public readonly contactPhone: string | null,
    public readonly dureeSurfacageMin: number,
    public readonly dureeMatchPouleMin: number,
    public readonly dureeMatchFinalMin: number,
    public readonly affichagePlanningPublic: boolean,
    public readonly msgBienvenue: string | null,
    public readonly msgFaisonsConnaissance: string | null,
    public readonly msgSelectionEquipe: string | null,
    public readonly msgAjoutEquipe: string | null,
    public readonly msgInscriptionEnCours: string | null,
    public readonly msgInscriptionValidee: string | null,
    public readonly msgLancerDemande: string | null,
    public readonly msgDemandeSoumise: string | null,
    public readonly msgListeAttente: string | null,
    public readonly msgPaiementAttendu: string | null,
    public readonly msgChequeInfo1: string | null,
    public readonly msgChequeInfo2: string | null,
    public readonly msgInscriptionConfirmee: string | null,
    public readonly msgRenseigneJoueurs: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}
}
