export enum InscriptionStatut {
  CANDIDATE = 'CANDIDATE',
  RESERVEE = 'RESERVEE',
  LISTE_ATTENTE = 'LISTE_ATTENTE',
  PAIEMENT_ATTENDU = 'PAIEMENT_ATTENDU',
  VALIDEE = 'VALIDEE',
  DOSSIER_EN_COURS = 'DOSSIER_EN_COURS',
  DOSSIER_COMPLET = 'DOSSIER_COMPLET',
  REFUSEE = 'REFUSEE',
}
