import { InscEdition } from '@prisma/client';
import { Edition } from '../../domain/entities/edition.entity';

export function toEditionEntity(raw: InscEdition): Edition {
  return new Edition(
    raw.id,
    raw.nom,
    raw.categorie,
    raw.annee,
    raw.etape,
    raw.dateDebut,
    raw.dateFinDebut,
    raw.dateFinFin,
    raw.dateDbutRepas,
    Number(raw.fraisInscription),
    Number(raw.prixRepas),
    raw.nbPlacesMax,
    raw.imageUrl,
    raw.imageDossierUrl,
    raw.imageRibUrl,
    raw.contactEmail,
    raw.contactPhone,
    raw.dureeSurfacageMin,
    raw.dureeMatchPouleMin,
    raw.dureeMatchFinalMin,
    raw.affichagePlanningPublic,
    raw.msgBienvenue,
    raw.msgFaisonsConnaissance,
    raw.msgSelectionEquipe,
    raw.msgAjoutEquipe,
    raw.msgInscriptionEnCours,
    raw.msgInscriptionValidee,
    raw.msgLancerDemande,
    raw.msgDemandeSoumise,
    raw.msgListeAttente,
    raw.msgPaiementAttendu,
    raw.msgChequeInfo1,
    raw.msgChequeInfo2,
    raw.msgInscriptionConfirmee,
    raw.msgRenseigneJoueurs,
    raw.createdAt,
    raw.updatedAt,
  );
}
