ALTER TABLE `presentation_articles`
  ADD COLUMN IF NOT EXISTS `surtitre` VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `surtitre_en` VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `faits` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `faits_en` TEXT NULL;
